Repository jenkins-x/prow-config-tekton, pull requests merged in 2019-06, with the labels that each got.

#74 add lifecycle periodic job
  prow/config.yaml
Labels: size/M

#78 add rottem and close periodic jobs for Jenkins X
  prow/config.yaml
Labels: size/M

#79 add cloudbees/jx-tenant-service
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#82 chore: add the parameter to the bdd context
  prow/config.yaml
Labels: size/XS

#83 chore: add the images context for the jx repo
  prow/config.yaml
Labels: size/S

#86 Revert "chore: add bdd context for release jobs"
  prow/config.yaml
Labels: size/XS

#87 chore: attempt to disable required-if-present-contexts for jx
  prow/config.yaml
Labels: size/XS

#93 Revert "feat: removed hound from the required context"
  prow/config.yaml
Labels: size/XS

#96 chore: unit tests are run as part of a separate context
  prow/config.yaml
Labels: size/XS

#97 add terraform-jx-templates-gke
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#99 Revert "chore: unit tests are run as part of a separate context"
  prow/config.yaml
Labels: size/XS

#100 chore: switching to rebase merge strategy for jx repo
  prow/config.yaml
Labels: size/XS
