Repository jenkins-x/prow-config-tekton, pull requests merged in 2019-04, with the labels that each got.

#1 add base files
  prow/config.yaml
  prow/plugins.yaml
Labels: size/L

#2 add initial repo to check things work on new cluster
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#3 add buiders base image and jx
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#6 feat: added jenkins-x-builder-base config
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#8 enable tide config for jx that checks for lgtm flag
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#7 feat: added jenkins-x-serverless-filerunner & jenkins-x-serverless config
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#9 feat: add job status url
  prow/config.yaml
Labels: size/XS

#10 firm up approvals for merging into jx infra
  prow/config.yaml
Labels: size/S

#11 feat: added homebrew-jx config
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#12 feat: added config for jx-docs & jx-tutorials
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#14 feat: added dev-env & updatebot config
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#15 feat: added jenkins-x-image config
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#16 Added dev-env-base to prow config
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#17 feat: added config for jenkins-x-charts
  prow/config.yaml
  prow/plugins.yaml
Labels: size/L

#18 feat: added config for jenkins-x-apps
  prow/config.yaml
  prow/plugins.yaml
Labels: size/L

#19 feat: added jenkins-x-versions config
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#20 feat: added config for core-frontend/core-backend
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#22 fix job_url_template is just a URL
  prow/config.yaml
Labels: size/XS

#27 feat: added jx-datadog config
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#29 Add config for jx-app-jacoco
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#28 fix: removed config-updater from repos that shouldn't have it
  prow/plugins.yaml
Labels: size/S

#30 feat: adding config for sso-operator
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#34 Add datadog app
  prow/config.yaml
  prow/plugins.yaml
Labels: size/S

#36 fix: add tiller bdd test
  prow/config.yaml
Labels: size/XS

#38 feat: add bucketrepo project
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#39 add cloudbees/jx-app-ui
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#35 Add eks tekton context
  prow/config.yaml
Labels: size/XS

#43 chore: readd the slack app
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#42 Tekton context for JX
  prow/config.yaml
Labels: size/XS
