Repository jenkins-x/prow-config-tekton, pull requests merged in 2019-07, with the labels that each got.

#101 fix: add a jx boot bdd test
  prow/config.yaml
Labels: size/XS

#102 temp: disabling terraform builds
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#104 Revert "temp: disabling terraform builds"
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#106 chore: Turn on Tekton BDD for jx PRs
  prow/config.yaml
Labels: size/XS

#107 add config for lighthouse
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#109 chore: Run tekton and bdd for jx.git on postsubmit to master
  prow/config.yaml
Labels: size/S

#110 Enable auto running bdd tests on PR
  prow/config.yaml
Labels: size/S

#111 feat: add prow-pipeline-controller to config
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#112 fix: enable CI/CD for go-scm
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#113 chore: Adding jenkins-x-builders-ml repo
  prow/config.yaml
Labels: size/S

#114 chore: add jenkins-x-builders-ml to plugins.yaml
  prow/plugins.yaml
Labels: size/S

#115 feat: adding cloudbees jenkins x versions repo
  prow/config.yaml
  prow/plugins.yaml
Labels: size/S

#116 fix: moved cloudbees-jenkins-x-versions to the right org
  prow/config.yaml
Labels: size/XS

#117 fix: fixed jenkins-x-versions position in the config file
  prow/config.yaml
Labels: size/S

#118 fix: add vault, storage + lighthouse bdd tests
  prow/config.yaml
Labels: size/S

#120 add dex
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#121 fix: add BDD tests for GHE + bitbucket server with lighthouse
  prow/config.yaml
Labels: size/S

#119 feat: add support for jenkins-x/test-infra
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#122 feat: separating terraform tests into static & tekton
  prow/config.yaml
Labels: size/S

#124 fix: lets always run the boot prow BDD tests
  prow/config.yaml
Labels: size/S

#123 chore: added precommit configuration
  .pre-commit-config.yaml
  .secrets.baseline
Labels: size/M
