Repository jenkins-x/prow-config-tekton, pull requests merged in 2019-08, with the labels that each got.

#125 fix: Add updatebot approval for jenkins-x-builders-ml
  prow/config.yaml
Labels: size/XS

#126 fix: add a release pipeline to the version stream
  prow/config.yaml
Labels: size/XS

#127 feat: turing off production env postsubmit to enable multicluster
  prow/config.yaml
Labels: size/XS

#128 feat: Add ui backup repos
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#129 chore: Remove baseline tekton and bdd for codecov on jx releases
  prow/config.yaml
Labels: size/S

#130 fix: lets always run the lighthouse BDD tests for github + GHE
  prow/config.yaml
Labels: size/XS

#131 feat: Add devpod context
  prow/config.yaml
Labels: size/XS

#132 chore: add jx-app-ui config
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#134 chore: enable tide for versions
  prow/config.yaml
Labels: size/XS
