Repository jenkins-x/prow-config-tekton, pull requests merged in 2019-05, with the labels that each got.

#46 Added jx-app-cert-manager
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#47 Update config.yaml
  prow/config.yaml
  prow/plugins.yaml
Labels: size/S

#49 add prometheous app
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#55 Remove all from tekton context in jx
  prow/config.yaml
Labels: size/XS

#56 add missing jobs
  prow/config.yaml
Labels: size/S

#57 Remove eks tekton
  prow/config.yaml
Labels: size/XS

#58 Update config.yaml
  prow/config.yaml
Labels: size/XS

#60 Update config.yaml
  prow/config.yaml
Labels: size/XS

#62 configure contexts for jx
  prow/config.yaml
Labels: size/S

#65 fix the context for codecov
  prow/config.yaml
Labels: size/XS

#66 fix: Switch name of jx postsubmit job
  prow/config.yaml
Labels: size/XS

#67 Add tests for eks classic
  prow/config.yaml
Labels: size/XS

#68 feat: added helm3 context for jenkins-x-versions
  prow/config.yaml
Labels: size/XS

#70 feat: start to enable spyglass
  prow/config.yaml
Labels: size/XS

#73 feat: added terraform context for jenkins-x-versions
  prow/config.yaml
Labels: size/XS
